services:
  - type: web
    name: telegram-bot-marketplace
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: n8n start
    envVars:
      - key: N8N_PORT
        value: 3000
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: false
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin@example.com
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Vbmjkl23312
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        value: your_telegram_bot_token
      - key: OPENAI_API_KEY
        value: your_openai_api_key
      - key: REPLICATE_API_TOKEN
        value: your_replicate_api_token
      - key: STRIPE_SECRET_KEY
        value: your_stripe_secret_key
      - key: N8N_SECURITY_OAUTH2_DISABLED
        value: true
      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_DIAGNOSTICS_ENABLED
        value: false 